In [1]:
import gym
import numpy as np

In [2]:
env=gym.make("FrozenLake-v0")

In [3]:
env.reset()
env.render()


SFFF
FHFH
FFFH
HFFG


In [28]:
def compute_value_function(policy):
    num_iterations=1000
    threshold=1e-20
    gamma=1.0
    value_table=np.zeros(env.observation_space.n)
    
    for i in range(num_iterations):
        updated_value_table=np.copy(value_table)
        
        for s in range(env.observation_space.n):
            a=policy[s]
            value_table[s]=sum([prob*(r + gamma * updated_value_table[s_]) for prob,s_,r,_ in env.P[s][a]])
            
        if (np.sum((np.fabs(updated_value_table-value_table))) <=threshold):
                break
    return value_table    
    

In [35]:
def extract_policy(value_table):
    gamma=1.0
    policy=np.zeros(env.observation_space.n)
    for s in range(env.observation_space.n):
        Q_values=[sum([prob*(r+gamma*value_table[s_]) for prob,s_,r,_ in env.P[s][a]]) for a in range(env.action_space.n)]
        policy[s]=np.argmax(np.array(Q_values))  
    return policy

In [38]:
env.reset()
policy=np.zeros(env.observation_space.n)

In [39]:
value_table=compute_value_function(policy)

In [40]:
print(value_table)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [41]:
policy=extract_policy(value_table)

In [43]:
print(policy)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]


In [45]:
def policy_iteration(env):
    num_iteration=1000
    policy=np.zeros(env.observation_space.n)
    
    for i in range(num_iteration):
        value_function=compute_value_function(policy)
        new_policy=extract_policy(value_function)
        
        if (np.all(policy==new_policy)):
            break
        policy=new_policy
        
    return policy    

In [46]:
optimal_policy=policy_iteration(env)

In [47]:
print(optimal_policy)

[0. 3. 3. 3. 0. 0. 0. 0. 3. 1. 0. 0. 0. 2. 1. 0.]


In [48]:
env.reset()
for i in range(len(policy)):
    print ("State: {} , Action {}".format(i,int(policy[i])))
    env.step(int(policy[i]))
    env.render()

State: 0 , Action 0
  (Left)
SFFF
FHFH
FFFH
HFFG
State: 1 , Action 0
  (Left)
SFFF
FHFH
FFFH
HFFG
State: 2 , Action 0
  (Left)
SFFF
FHFH
FFFH
HFFG
State: 3 , Action 0
  (Left)
SFFF
FHFH
FFFH
HFFG
State: 4 , Action 0
  (Left)
SFFF
FHFH
FFFH
HFFG
State: 5 , Action 0
  (Left)
SFFF
FHFH
FFFH
HFFG
State: 6 , Action 0
  (Left)
SFFF
FHFH
FFFH
HFFG
State: 7 , Action 0
  (Left)
SFFF
FHFH
FFFH
HFFG
State: 8 , Action 0
  (Left)
SFFF
FHFH
FFFH
HFFG
State: 9 , Action 0
  (Left)
SFFF
FHFH
FFFH
HFFG
State: 10 , Action 0
  (Left)
SFFF
FHFH
FFFH
HFFG
State: 11 , Action 0
  (Left)
SFFF
FHFH
FFFH
HFFG
State: 12 , Action 0
  (Left)
SFFF
FHFH
FFFH
HFFG
State: 13 , Action 0
  (Left)
SFFF
FHFH
FFFH
HFFG
State: 14 , Action 1
  (Down)
SFFF
FHFH
FFFH
HFFG
State: 15 , Action 0
  (Left)
SFFF
FHFH
FFFH
HFFG
